name: Lint

on: workflow_call

jobs:

  kotlin:

    name: Lint Kotlin files
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Detekt analysis
        run: ./gradlew detekt
