name: Lint

on: workflow_call

jobs:

  kotlin:

    name: Lint Kotlin files
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Detekt analysis
        run: ./gradlew detekt

  shell:
    name: Lint Shell files
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: ShellCheck analysis
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: "./scripts"
