name: Test

on: workflow_call

jobs:

  unit-tests:

    name: Unit tests
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      #- name: Run unit tests on JVM for Multiplatform modules
      #  run: ./gradlew jvmTest

      - name: Run unit tests for JVM only and Android modules
        run: ./gradlew test
